apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - cilium.yaml
  - external-dns.yaml
  - freenas-api-iscsi.yaml
  - freenas-api-nfs.yaml
  - snapshot-controller.yaml
