apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: elliptic_prancing709@dungeonmail.com
    # The server is replaced in /clusters/talos/infrastructure.yaml
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          cloudflare:
            email: geography_chemo535@dungeonmail.com
            apiTokenSecretRef:
              # Managed in kubernetes-secrets repo
              name: cloudflare-api-token
              key: api-token
