---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # Override to match Let's Encrypt e-mail
    email: 30529916+barstown@users.noreply.github.com
    # The server is replaced in /clusters/talos/infrastructure.yaml
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          cloudflare:
            # Override to match Cloudflare account email
            email: 30529916+barstown@users.noreply.github.com
            apiTokenSecretRef:
              # Managed in kubernetes-secrets repo
              name: cloudflare-api-token-secret
              key: api-token
